version: "3"

output: prefixed

dotenv: ['.env']

env:
  STATIC_DIR: "internal/ui/static"

tasks:
  # The `build:` tasks below are used together for production builds of a project
  build:templ:
    cmds:
      - go tool templ generate

  build:lit:
    cmds:
      - pnpm run build:lit

  build:styles:
    cmds:
      - pnpm run build:styles

  build:
    cmds:
      - go build -tags=prod -o bin/main ./cmd/web
    deps:
      - build:templ
      - build:lit
      - build:styles

  # Use this task to debug with the delve debugger
  debug:
    cmds:
      - go tool dlv exec ./bin/main
    deps:
      - build

  # The `live:` tasks below are used together for development builds and will live-reload the server
  live:templ:
    cmds:
      - go tool templ generate --watch --proxy="http://localhost:${PORT:-8080}" --open-browser=false

  live:lit:
    cmds:
      - pnpm run watch:lit

  live:styles:
    cmds:
      - pnpm run watch:styles

  live:server:
    cmds:
      - |
        go tool air  \
         -build.cmd "go build -tags=dev -o tmp/bin/main ./cmd/web" \
         -build.bin "tmp/bin/main" \
         -build.delay "100" \
         -build.exclude_dir "data,node_modules,internal/ui/libs/datastar/node_modules,internal/ui/libs/lit/node_modules" \
         -build.include_ext "go" \
         -build.stop_on_error "false" \
         -build.send_interrupt "true" \
         -build.kill_delay "200" \
         -misc.clean_on_exit "true"

  live:reload:
    cmds:
      - |
        mkdir -p tmp/reload && \
        go tool air \
        -build.cmd "go tool templ generate --notify-proxy" \
        -build.bin "true" \
        -build.delay "300" \
        -build.exclude_dir "" \
        -build.include_dir "$STATIC_DIR" \
        -build.include_ext "js,css" \
        -build.send_interrupt "true" \
        -build.kill_delay "200" \
        -tmp_dir "tmp/reload"

  live:
    deps:
      - live:templ
      - live:lit
      - live:styles
      - live:reload
      - live:server

  run:
    cmds:
      - ./bin/main
    deps:
      - build

  default:
    cmds:
      - task: live
