version: "3"

env:
  NATS_PORT: 4222
  STATIC_DIR: "web/resources/static"
  PREFER_STATIC_BINARIES: '{{default "false" .PREFER_STATIC_BINARIES}}'
  TAILWIND_BIN: '{{default "" .TAILWIND_BIN}}'

tasks:
  # The `build:` tasks below are used together for production builds of a project
  build:templ:
    cmds:
      - go tool templ generate
    sources:
      - "**/*.templ"
    generates:
      - "**/*_templ.go"

  build:styles:
    cmds:
      - |
        if [ "$PREFER_STATIC_BINARIES" = "true" ] && [ -n "$TAILWIND_BIN" ]; then
          $TAILWIND_BIN -i web/resources/styles/styles.css -o $STATIC_DIR/index.css --minify
        elif [ "$PREFER_STATIC_BINARIES" = "true" ] && command -v tailwindcss &> /dev/null; then
          tailwindcss -i web/resources/styles/styles.css -o $STATIC_DIR/index.css --minify
        else
          go tool gotailwind -i web/resources/styles/styles.css -o $STATIC_DIR/index.css
        fi
    sources:
      - "./web/resources/**/*.{html,ts,templ,go,css}"
    generates:
      - "{{.STATIC_DIR}}/index.css"

  build:wc:
    cmds:
      - go run cmd/web/build/main.go
    sources:
      - "./web/libs/**/**/*.{html,css,ts}"
    generates:
      - "{{.STATIC_DIR}}/libs/**"

  build:
    cmds:
      - go build -tags=prod -o bin/main ./cmd/web
    deps:
      - build:templ
      - build:styles
      - build:wc

  # Use this task to debug with the delve debugger
  debug:
    cmds:
      - go tool dlv exec ./bin/main
    deps:
      - build

  # Use this task to download latest version of client libs
  download:
    cmds:
      - go run cmd/downloader/main.go

  # The `live:` tasks below are used together for development builds and will live-reload the server
  live:templ:
    cmds:
      - go tool templ generate -watch

  live:styles:
    cmds:
      - |
        if [ "$PREFER_STATIC_BINARIES" = "true" ] && [ -n "$TAILWIND_BIN" ]; then
          echo "✓ Using $TAILWIND_BIN (via PREFER_STATIC_BINARIES)"
          $TAILWIND_BIN -i web/resources/styles/styles.css -o $STATIC_DIR/index.css --watch
        elif [ "$PREFER_STATIC_BINARIES" = "true" ] && command -v tailwindcss &> /dev/null; then
          echo "✓ Using system tailwindcss (via PREFER_STATIC_BINARIES)"
          tailwindcss -i web/resources/styles/styles.css -o $STATIC_DIR/index.css --watch
        else
          go tool gotailwind -i web/resources/styles/styles.css -o $STATIC_DIR/index.css -w
        fi

  live:wc:
    cmds:
      - go run cmd/web/build/main.go -watch

  live:server:
    cmds:
      - |
        go tool air  \
         -build.cmd "go build -tags=dev -o tmp/bin/main ./cmd/web" \
         -build.bin "tmp/bin/main" \
         -build.exclude_dir "data,node_modules,web/resources/libs/datastar/node_modules,web/resources/libs/lit/node_modules" \
         -build.include_ext "go,templ" \
         -misc.clean_on_exit "true"

  live:
    deps:
      - live:templ
      - live:styles
      - live:wc
      - live:server

  run:
    cmds:
      - ./bin/main
    deps:
      - build

  default:
    cmds:
      - task: live
